name: 📦 Auto Release
on:
  push:
    tags:
      - 'v*' # Se activa cuando creas una etiqueta como v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # GitHub escribe lo que hiciste solo
